language: python
python:
  - '3.6'
env:
  - DEVFLAG=--dev DJANGO_DEBUG=True
  - DEVFLAG=
services:
  - docker
before_install:
  - sudo service postgresql stop
  - docker --version
  - docker-compose --version
install:
  - python thunorctl.py $DEVFLAG quickstart
script:
  - python thunorctl.py $DEVFLAG test
after_success:
  - if [[ $DEVFLAG == "--dev" ]]; then pip install coveralls; fi
  - if [[ $DEVFLAG == "--dev" ]]; then coveralls; fi
