language: python
python:
- '3.6'
env:
  matrix:
  - DEVFLAG=--dev
  - DEVFLAG=
services:
- docker
before_install:
- sudo service postgresql stop
- docker --version
- docker-compose --version
install:
- if [[ $DEVFLAG == "--dev" ]]; then python thunorbld.py init; fi
- if [[ $DEVFLAG == "" ]]; then python thunorbld.py testinit; fi
script:
- python thunorbld.py $DEVFLAG test
after_success:
- if [[ $DEVFLAG == "--dev" ]]; then pip install coveralls; fi
- if [[ $DEVFLAG == "--dev" ]]; then coveralls; fi
jobs:
  include:
  - stage: deploy
    env:
      secure: 5+alU5doQu9We59s9doQH6/LCg0iC2VkVrdhoLl2dTEdC56Z6bWQuhVGYAZ4csldWdNB5vOXf4MrnNfCb9EdFtgvX9PE3M2G3hlLP0p1APBUFtpR1jc9+CBUCHykqke9eQ5Lieu4xrVuKA4J7NIR3I7t4PIG1ltuujg9AcyqT9UnsFmnduFX+j/PS5OHdbZs8Hb+ng7/Wn0NezgJzeLCZC9eBmPZYYsmgcCj+Pj75iLj77KkOUR/TztD5CSNy//ooFI3jdv6CkOsSBtVwHjCs8qFOEnPZFwK6HRCEcun+MPf66+x5Bv360M+cCxi+wn+yPB4PO5AxJ4plXDGpM4JgHwpx6TKKQV1XUqAAIus2NKiYC+NGxoPGoLrS8VkJl6cJcO7EoImL/Lxm726N+MRmfR8gcYF0NM1KCCJRdrd6Fl3stfHbIP2WixyjFWzG2aXEXg+OVr7ZOaHHnFy21CeHXdRCLtOmomIKukHCQfQm3T6+kfbN08r0AdzT6hGMzgiVcwkWPURb/mxbNyzI4SBIXG52tc5dQtwriXJxp7hmC3sfnVVgDiSCvvjqbzmtN10/13+M9Vdiukf8EO5gITLBYkLT5J/jkITxtbqUnJVEiSb71J82qfnU1bHgJt3fzHdhjLT4ehM79gaeOzR/M7BvpR8Sh+EfndnWNe8UTxvL8s=
    install: skip
    script: ./docker-deploy.sh

