language: python
python:
  - '3.6'
services:
  - postgresql
  - docker
env:
  - DJANGO_DEBUG=False DJANGO_SECRET_KEY=asdf DJANGO_DATABASE=postgres POSTGRES_PASSWORD=
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - export DJANGO_EMAIL_HOST= DJANGO_EMAIL_PORT= DJANGO_EMAIL_USER= DJANGO_EMAIL_PASSWORD=
  - mkdir -p _state/thunor-files
  - export PYTHONPATH=thunor
  - python thunorctl.py --dev generatestatic
  - python manage.py collectstatic --no-input
script:
  - python manage.py test
after_success:
  - coveralls
