version: '2'
services:
  db:
    extends:
      file: docker-compose.base.yml
      service: db
  app:
    extends:
      file: docker-compose.base.yml
      service: app
    depends_on:
      - db

  nginx:
    image: nginx:mainline
    volumes:
      - ./_conf/nginx.base.conf:/etc/nginx/nginx.conf:ro
      - ./_conf/nginx.site.conf:/etc/nginx/nginx.site.conf:ro
      - ./_state/logs/nginx/:/var/log/nginx/
      - ./_state/thunor-files/:/srv/thunor-files/:ro
      - ./_state/thunor-static/:/srv/thunor-static/:ro
      - ./_state/certbot/:/etc/letsencrypt/:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
