version: '2.1'
services:
  app:
    image: alubbock/thunorweb:latest
  nginx:
    image: nginx:mainline
    ports:
      - "80:80"
      - "443:443"
  postgres10:
    image: postgres:10
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 60s
      timeout: 30s
      retries: 6
  postgres15:
    image: postgres:15
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 60s
      timeout: 30s
      retries: 6
  redis:
    image: redis:latest
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 60s
      timeout: 10s
      retries: 3

volumes:
  static-assets:
