version: '2.1'
services:
  db:
    image: postgres:9.6
    env_file:
      - ./_conf/thunor.env
    volumes:
      - ./_state/postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 6
