version: '2'
services:
  db:
    image: postgres:9.6
    env_file:
      - ./_conf/thunor.env
    volumes:
      - ./_state/postgres-data:/var/lib/postgresql/data
  web:
    build: .
    command: /bin/sh docker-entrypoint.sh
    volumes:
      - .:/thunor
    env_file:
      - ./_conf/thunor.env
