version: '2'

services:
  certbot:
    image: certbot/certbot
    entrypoint: ""
    volumes:
      - ./_state/certbot:/etc/letsencrypt
      - ./_state/thunor-static/.well-known:/thunor-static/.well-known
    environment:
      - TERM=xterm
