FROM python:3.6
ENV PYTHONUNBUFFERED 1

ENV THUNOR_HOME=/thunor

RUN mkdir $THUNOR_HOME
RUN chown $THUNOR_USER:$THUNOR_GROUP $THUNOR_HOME
WORKDIR $THUNOR_HOME
ADD requirements.txt $THUNOR_HOME
RUN pip install -r requirements.txt
ADD . $THUNOR_HOME
USER $THUNOR_USER
