version: '2'
services:
  db:
    image: postgres:9.6
    env_file:
      - ./_conf/thunor.env
    volumes:
      - ./_state/postgres-data:/var/lib/postgresql/data
  app:
    build: .
    volumes:
      - ./_state/thunor-files:/thunor/_state/thunor-files
      - ./_state/thunor-static/webpack-stats.json:/thunor/_state/thunor-static/webpack-stats.json:ro
    env_file:
      - ./_conf/thunor.env
