# Generated by Django 4.2.16 on 2024-09-03 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import thunor.io


class Migration(migrations.Migration):

    replaces = [
        ("thunorweb", "0001_squashed_0011_automatic_controls"),
        ("thunorweb", "0002_dataset_delete_flag"),
        ("thunorweb", "0003_dataset_admin"),
        ("thunorweb", "0004_optim_indexes"),
        ("thunorweb", "0005_drop_duplicate_idxs"),
    ]

    dependencies = [
        ("auth", "0008_alter_user_username_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CellLine",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Drug",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="HTSDataset",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_date",
                    models.DateTimeField(default=None, editable=False, null=True),
                ),
            ],
            options={
                "permissions": (
                    ("view_plots", "View plots"),
                    ("view_plate_layout", "View plate layout"),
                    ("download_data", "Download data"),
                ),
                "verbose_name": "HTS Dataset",
            },
        ),
        migrations.CreateModel(
            name="Plate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("last_annotated", models.DateTimeField(null=True)),
                ("width", models.IntegerField()),
                ("height", models.IntegerField()),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="thunorweb.htsdataset",
                    ),
                ),
                ("expt_date", models.DateField(null=True)),
                ("expt_id", models.TextField(null=True)),
            ],
            options={
                "unique_together": {("dataset", "name")},
            },
            bases=(models.Model, thunor.io.PlateMap),
        ),
        migrations.CreateModel(
            name="PlateFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("file", models.FileField(upload_to="plate-files")),
                ("file_format", models.TextField(null=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="thunorweb.htsdataset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Well",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("well_num", models.IntegerField()),
                (
                    "cell_line",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="thunorweb.cellline",
                    ),
                ),
                (
                    "plate",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="thunorweb.plate",
                    ),
                ),
            ],
            options={
                "unique_together": {("plate", "well_num")},
            },
        ),
        migrations.CreateModel(
            name="HTSDatasetUserObjectPermission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="thunorweb.htsdataset",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.permission",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("user", "permission", "content_object")},
            },
        ),
        migrations.CreateModel(
            name="HTSDatasetGroupObjectPermission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="thunorweb.htsdataset",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="auth.group"
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.permission",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("group", "permission", "content_object")},
            },
        ),
        migrations.CreateModel(
            name="DeletedHTSDataset",
            fields=[],
            options={
                "verbose_name": "Deleted HTS Dataset",
                "proxy": True,
                "indexes": [],
            },
            bases=("thunorweb.htsdataset",),
        ),
        migrations.CreateModel(
            name="WellStatistic",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stat_name", models.TextField()),
                ("stat_date", models.DateTimeField(auto_now=True)),
                ("value", models.FloatField(null=True)),
                (
                    "well",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="thunorweb.well"
                    ),
                ),
            ],
            options={
                "unique_together": {("well", "stat_name")},
            },
        ),
        migrations.CreateModel(
            name="CellLineTag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag_name", models.TextField()),
                (
                    "cell_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="thunorweb.cellline",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("tag_name", "owner", "cell_line")},
            },
        ),
        migrations.CreateModel(
            name="DrugTag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag_name", models.TextField()),
                (
                    "drug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="thunorweb.drug"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("tag_name", "owner", "drug")},
            },
        ),
        migrations.CreateModel(
            name="WellDrug",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dose", models.FloatField(null=True)),
                (
                    "drug",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="thunorweb.drug",
                    ),
                ),
                (
                    "well",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="thunorweb.well",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField()),
            ],
            options={
                "unique_together": {("well", "drug"), ("well", "order")},
            },
        ),
        migrations.CreateModel(
            name="WellMeasurement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assay", models.TextField()),
                ("timepoint", models.DurationField()),
                ("value", models.FloatField(null=True)),
                (
                    "well",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="thunorweb.well",
                    ),
                ),
            ],
            options={
                "unique_together": {("well", "assay", "timepoint")},
            },
        ),
    ]
