# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-17 20:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import thunor.io


class Migration(migrations.Migration):

    replaces = [('thunorweb', '0001_initial'), ('thunorweb', '0002_add_drug_order'), ('thunorweb', '0003_allow_null_drugs_doses'), ('thunorweb', '0004_dataset_permissions'), ('thunorweb', '0005_base_dataset_permissions'), ('thunorweb', '0006_expt_id_date'), ('thunorweb', '0007_control_handling'), ('thunorweb', '0008_well_statistics'), ('thunorweb', '0009_allow_null_well_statistic'), ('thunorweb', '0010_cell_line_and_drug_tags'), ('thunorweb', '0011_automatic_controls')]

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CellLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HTSDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('last_annotated', models.DateTimeField(null=True)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thunorweb.HTSDataset')),
            ],
            bases=(models.Model, thunor.io.PlateMap),
        ),
        migrations.CreateModel(
            name='PlateFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='plate-files')),
                ('file_format', models.TextField(null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thunorweb.HTSDataset')),
            ],
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('well_num', models.IntegerField()),
                ('cell_line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='thunorweb.CellLine')),
                ('plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thunorweb.Plate')),
            ],
        ),
        migrations.CreateModel(
            name='WellDrug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose', models.FloatField(null=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thunorweb.Drug')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thunorweb.Well')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WellMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assay', models.TextField()),
                ('timepoint', models.DurationField()),
                ('value', models.FloatField(null=True)),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thunorweb.Well')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='wellmeasurement',
            unique_together=set([('well', 'assay', 'timepoint')]),
        ),
        migrations.AlterIndexTogether(
            name='wellmeasurement',
            index_together=set([('well', 'assay', 'timepoint')]),
        ),
        migrations.AlterUniqueTogether(
            name='welldrug',
            unique_together=set([('well', 'drug')]),
        ),
        migrations.AlterIndexTogether(
            name='welldrug',
            index_together=set([('well', 'drug')]),
        ),
        migrations.AlterUniqueTogether(
            name='well',
            unique_together=set([('plate', 'well_num')]),
        ),
        migrations.AlterIndexTogether(
            name='well',
            index_together=set([('plate', 'well_num')]),
        ),
        migrations.AddField(
            model_name='plate',
            name='expt_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='plate',
            name='expt_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='plate',
            unique_together=set([('dataset', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='welldrug',
            unique_together=set([('well', 'order'), ('well', 'drug')]),
        ),
        migrations.AlterField(
            model_name='welldrug',
            name='drug',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='thunorweb.Drug'),
        ),
        migrations.AlterIndexTogether(
            name='welldrug',
            index_together=set([('well', 'drug', 'order')]),
        ),
        migrations.CreateModel(
            name='HTSDatasetGroupObjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thunorweb.HTSDataset')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HTSDatasetUserObjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thunorweb.HTSDataset')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='htsdatasetuserobjectpermission',
            unique_together=set([('user', 'permission', 'content_object')]),
        ),
        migrations.AlterUniqueTogether(
            name='htsdatasetgroupobjectpermission',
            unique_together=set([('group', 'permission', 'content_object')]),
        ),
        migrations.AlterModelOptions(
            name='htsdataset',
            options={'permissions': (('view_plots', 'View plots'), ('view_plate_layout', 'View plate layout'), ('download_data', 'Download data'))},
        ),
        migrations.CreateModel(
            name='WellStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_name', models.TextField()),
                ('stat_date', models.DateTimeField(auto_now=True)),
                ('value', models.FloatField(null=True)),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thunorweb.Well')),
            ],
        ),
        migrations.CreateModel(
            name='CellLineTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.TextField()),
                ('cell_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thunorweb.CellLine')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DrugTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.TextField()),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thunorweb.Drug')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='drugtag',
            unique_together=set([('tag_name', 'owner', 'drug')]),
        ),
        migrations.AlterIndexTogether(
            name='drugtag',
            index_together=set([('tag_name', 'owner', 'drug')]),
        ),
        migrations.AlterUniqueTogether(
            name='celllinetag',
            unique_together=set([('tag_name', 'owner', 'cell_line')]),
        ),
        migrations.AlterIndexTogether(
            name='celllinetag',
            index_together=set([('tag_name', 'owner', 'cell_line')]),
        ),
    ]
