# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thunorweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='welldrug',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='welldrug',
            unique_together=set([('well', 'order'), ('well', 'drug')]),
        ),
    ]
