# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-05 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thunorweb', '0003_dataset_admin'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wellstatistic',
            unique_together=set([('well', 'stat_name')]),
        ),
        migrations.AlterIndexTogether(
            name='celllinetag',
            index_together=set([]),
        ),
        migrations.AlterIndexTogether(
            name='drugtag',
            index_together=set([]),
        ),
        migrations.AlterIndexTogether(
            name='well',
            index_together=set([]),
        ),
        migrations.AlterIndexTogether(
            name='welldrug',
            index_together=set([]),
        ),
        migrations.AlterIndexTogether(
            name='wellmeasurement',
            index_together=set([]),
        ),
    ]
