# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-07 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thunorweb', '0004_optim_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='plate',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='thunorweb.Plate'),
        ),
        migrations.AlterField(
            model_name='welldrug',
            name='well',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='thunorweb.Well'),
        ),
        migrations.AlterField(
            model_name='wellmeasurement',
            name='well',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='thunorweb.Well'),
        ),
    ]
