# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-08 05:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thunorweb', '0005_drop_duplicate_idxs'),
    ]

    operations = [
        migrations.AddField(
            model_name='celllinetag',
            name='tag_category',
            field=models.TextField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='celllinetag',
            unique_together=set([('owner', 'tag_name', 'cell_line', 'tag_category')]),
        ),
    ]
