# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-30 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thunorweb', '0006_expt_id_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='htsdataset',
            name='control_handling',
            field=models.TextField(null=True),
        ),
    ]
