# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-09 05:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('thunorweb', '0008_curvefit'), ('thunorweb', '0009_auto_20180409_0505')]

    dependencies = [
        ('thunorweb', '0007_tag_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurveFit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_type', models.CharField(db_index=True, max_length=10)),
                ('viability_time', models.DurationField(db_index=True, null=True)),
                ('curve_fit_class', models.CharField(max_length=20, null=True)),
                ('fit_params', models.BinaryField()),
                ('max_dose', models.FloatField()),
                ('min_dose', models.FloatField()),
                ('emax_obs', models.FloatField()),
                ('cell_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thunorweb.CellLine')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thunorweb.HTSDataset')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thunorweb.Drug')),
            ],
        ),
    ]
