# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thunorweb', '0007_control_handling'),
    ]

    operations = [
        migrations.CreateModel(
            name='WellStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_name', models.TextField()),
                ('stat_date', models.DateTimeField(auto_now=True)),
                ('value', models.FloatField()),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thunorweb.Well')),
            ],
        ),
        migrations.AlterField(
            model_name='htsdataset',
            name='control_handling',
            field=models.TextField(choices=[(None, 'Unspecified'), ('A1', 'Well A1')], null=True),
        ),
    ]
