# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 06:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thunorweb', '0009_allow_null_well_statistic'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellLineTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.TextField()),
                ('cell_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thunorweb.CellLine')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DrugTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.TextField()),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thunorweb.Drug')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='drugtag',
            unique_together=set([('tag_name', 'owner', 'drug')]),
        ),
        migrations.AlterIndexTogether(
            name='drugtag',
            index_together=set([('tag_name', 'owner', 'drug')]),
        ),
        migrations.AlterUniqueTogether(
            name='celllinetag',
            unique_together=set([('tag_name', 'owner', 'cell_line')]),
        ),
        migrations.AlterIndexTogether(
            name='celllinetag',
            index_together=set([('tag_name', 'owner', 'cell_line')]),
        ),
    ]
