# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-25 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from datetime import timedelta
from django.utils import timezone


def create_curve_fit_sets(apps, schema_editor):
    CurveFitSet = apps.get_model('thunorweb.CurveFitSet')
    CurveFit = apps.get_model('thunorweb.CurveFit')

    sets = CurveFit.objects.values('dataset_id', 'stat_type',
                                   'viability_time').distinct()
    for cfs in sets:
        now = timezone.now()
        cfs_new = CurveFitSet.objects.create(
            dataset_id=cfs['dataset_id'],
            stat_type=cfs['stat_type'],
            viability_time=cfs['viability_time'] if cfs['viability_time'] is
                not None else timedelta(0),
            fit_protocol=1,
            calculation_start=now,
            calculation_end=now
        )

        CurveFit.objects.filter(
            dataset_id=cfs['dataset_id'],
            stat_type=cfs['stat_type'],
            viability_time=cfs['viability_time']
        ).update(fit_set=cfs_new)


class Migration(migrations.Migration):

    dependencies = [
        ('thunorweb', '0011_tagperms'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurveFitSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_type', models.CharField(max_length=10)),
                ('viability_time', models.DurationField()),
                ('fit_protocol', models.IntegerField()),
                ('calculation_start', models.DateTimeField()),
                ('calculation_end', models.DateTimeField(null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thunorweb.HTSDataset')),
            ],
        ),
        migrations.AddField(
            model_name='curvefit',
            name='fit_set',
            field=models.ForeignKey(null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='thunorweb.CurveFitSet'),
        ),
        migrations.RunPython(create_curve_fit_sets),
        migrations.AlterField(
            model_name='curvefit',
            name='fit_set',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='thunorweb.CurveFitSet'),
        ),
        migrations.RemoveField(
            model_name='curvefit',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='curvefit',
            name='stat_type',
        ),
        migrations.RemoveField(
            model_name='curvefit',
            name='viability_time',
        ),
        migrations.AlterUniqueTogether(
            name='curvefitset',
            unique_together=set([('dataset', 'stat_type', 'viability_time')]),
        ),
    ]
