# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-15 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thunorweb', '0013_datasetfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='curvefit',
            name='aa_obs',
            field=models.FloatField(null=True),
        ),
    ]
