# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 18:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pyhts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CellLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HTSDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('last_annotated', models.DateTimeField(null=True)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyhts.HTSDataset')),
            ],
            bases=(models.Model, pyhts.models.PlateMap),
        ),
        migrations.CreateModel(
            name='PlateFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='')),
                ('file_format', models.TextField(null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyhts.HTSDataset')),
            ],
        ),
        migrations.CreateModel(
            name='WellCellLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('well', models.IntegerField()),
                ('cell_line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pyhts.CellLine')),
                ('plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyhts.Plate')),
            ],
        ),
        migrations.CreateModel(
            name='WellDrug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('well', models.IntegerField()),
                ('dose', models.FloatField()),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyhts.Drug')),
                ('plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyhts.Plate')),
            ],
        ),
        migrations.CreateModel(
            name='WellMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('well', models.IntegerField()),
                ('assay', models.TextField()),
                ('timepoint', models.DurationField()),
                ('value', models.FloatField(null=True)),
                ('plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyhts.Plate')),
            ],
        ),
        migrations.AddField(
            model_name='plate',
            name='plate_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyhts.PlateFile'),
        ),
        migrations.AlterUniqueTogether(
            name='wellmeasurement',
            unique_together=set([('plate', 'well', 'assay', 'timepoint')]),
        ),
        migrations.AlterUniqueTogether(
            name='welldrug',
            unique_together=set([('plate', 'well', 'drug')]),
        ),
        migrations.AlterUniqueTogether(
            name='wellcellline',
            unique_together=set([('plate', 'well')]),
        ),
        migrations.AlterUniqueTogether(
            name='plate',
            unique_together=set([('dataset', 'name')]),
        ),
    ]
