# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-04 01:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pyhts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CellLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DrugInWell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose', models.FloatField()),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyhts.Drug')),
            ],
        ),
        migrations.CreateModel(
            name='HTSDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('timepoint_secs', models.IntegerField(null=True)),
            ],
            bases=(models.Model, pyhts.models.PlateMap),
        ),
        migrations.CreateModel(
            name='PlateFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('process_date', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(upload_to=b'')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyhts.HTSDataset')),
            ],
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('well_no', models.IntegerField()),
                ('cell_line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pyhts.CellLine')),
                ('plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyhts.Plate')),
            ],
        ),
        migrations.CreateModel(
            name='WellMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assay', models.TextField()),
                ('value', models.FloatField()),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyhts.Well')),
            ],
        ),
        migrations.AddField(
            model_name='plate',
            name='plate_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyhts.PlateFile'),
        ),
        migrations.AddField(
            model_name='druginwell',
            name='well',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyhts.Well'),
        ),
        migrations.AlterUniqueTogether(
            name='wellmeasurement',
            unique_together=set([('well', 'assay')]),
        ),
        migrations.AlterUniqueTogether(
            name='well',
            unique_together=set([('plate', 'well_no')]),
        ),
        migrations.AlterUniqueTogether(
            name='druginwell',
            unique_together=set([('well', 'drug')]),
        ),
    ]
