# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyhts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellline',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
