# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-31 20:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pyhts', '0001_squashed_0003_drug'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugInWell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose', models.FloatField()),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyhts.Drug')),
            ],
        ),
        migrations.CreateModel(
            name='HTSDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_name', models.TextField()),
                ('plate_size', models.IntegerField()),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyhts.HTSDataset')),
                ('plate_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyhts.PlateFile')),
            ],
        ),
        migrations.CreateModel(
            name='PlateAssay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assay', models.TextField()),
                ('plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyhts.Plate')),
            ],
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('well_no', models.IntegerField()),
                ('plate_assay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyhts.PlateAssay')),
            ],
        ),
        migrations.AddField(
            model_name='druginwell',
            name='well',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyhts.Well'),
        ),
        migrations.AlterUniqueTogether(
            name='well',
            unique_together=set([('plate_assay', 'well_no')]),
        ),
        migrations.AlterUniqueTogether(
            name='plateassay',
            unique_together=set([('plate', 'assay')]),
        ),
        migrations.AlterUniqueTogether(
            name='plate',
            unique_together=set([('dataset', 'plate_file')]),
        ),
        migrations.AlterUniqueTogether(
            name='druginwell',
            unique_together=set([('well', 'drug')]),
        ),
    ]
