# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyhts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platefile',
            name='file',
            field=models.FileField(upload_to='plate-files'),
        ),
    ]
