# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyhts', '0002_auto_20161112_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellmeasurement',
            name='value',
            field=models.FloatField(null=True),
        ),
    ]
