# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 23:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyhts', '0002_add_drug_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welldrug',
            name='dose',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='welldrug',
            name='drug',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pyhts.Drug'),
        ),
        migrations.AlterIndexTogether(
            name='welldrug',
            index_together=set([('well', 'drug', 'order')]),
        ),
    ]
