# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-31 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyhts', '0003_auto_20161031_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='plate',
            name='timepoint_secs',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
