# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyhts', '0003_auto_20161115_0340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platefile',
            name='process_date',
        ),
        migrations.AddField(
            model_name='plate',
            name='last_annotated',
            field=models.DateTimeField(null=True),
        ),
    ]
