# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-03 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyhts', '0004_plate_timepoint_secs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plate',
            old_name='plate_size',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='plate',
            old_name='plate_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='plate',
            name='width',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plate',
            name='timepoint_secs',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='plate',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='plate',
            name='dataset',
        ),
    ]
