# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-03 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyhts', '0005_base_dataset_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='plate',
            name='expt_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='plate',
            name='expt_id',
            field=models.TextField(null=True),
        ),
    ]
