# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyhts', '0005_platefile_dataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='platefile',
            name='file_format',
            field=models.TextField(null=True),
        ),
    ]
