# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-30 22:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyhts', '0010_cell_line_and_drug_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='htsdataset',
            name='control_handling',
        ),
    ]
