version: '2.1'
services:
  app:
    extends:
      file: docker-compose.services.yml
      service: app
    environment:
      - THUNOR_LOGIN_REQUIRED=True
      - THUNOR_SIGNUP_OPEN=False
      - DJANGO_SENTRY_DSN=
      - DJANGO_EMAIL_HOST=
      - DJANGO_EMAIL_PORT=587
      - DJANGO_EMAIL_USER=
      - DJANGO_EMAIL_PASSWORD=
      - DJANGO_EMAIL_FROM=
      - DJANGO_SECRET_KEY=
      - DJANGO_DEBUG=False
      - DJANGO_DATABASE=postgres
      - DJANGO_HOSTNAME=
      - DJANGO_STATIC_URL=/static/
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=thunor
      - POSTGRES_PASSWORD=
      - UWSGI_PROCESSES=5
      - UWSGI_BUFFER_SIZE=32768
    volumes:
      - $THUNORHOME/_state/thunor-static:/thunor/_state/thunor-static:ro
      - $THUNORHOME/_state/thunor-files:/thunor/_state/thunor-files
  nginx:
    extends:
      file: docker-compose.services.yml
      service: nginx
    volumes:
      - $THUNORHOME/_state/nginx-config/nginx.base.conf:/etc/nginx/nginx.conf:ro
      - $THUNORHOME/_state/nginx-config/nginx.site.conf:/etc/nginx/nginx.site.conf:ro
      - $THUNORHOME/_state/logs/nginx/:/var/log/nginx/
      - $THUNORHOME/_state/thunor-files/:/srv/thunor-files/:ro
      - $THUNORHOME/_state/thunor-static/:/srv/thunor-static/:ro
      - $THUNORHOME/_state/certbot/:/etc/letsencrypt/:ro
    depends_on:
      - app
  postgres:
    extends:
      file: docker-compose.services.yml
      service: postgres
    volumes:
      - $THUNORHOME/_state/postgres-data:/var/lib/postgresql/data
